export function getAcademicSeedData(tenantId = "cgu") {
  return [
    {
      _id: "support-1",
      tenantId,
      category: "support-contact",
      semester: 6,
      section: "A",
      classCoordinatorName: "Prof. A. Sharma",
      classCoordinatorEmail: "asharma@cgu.edu.in",
      classCoordinatorPhone: "9000000001",
      mentorName: "Dr. S. Panda",
      mentorEmail: "spanda@cgu.edu.in",
      mentorPhone: "9000000002",
      mentorRoom: "Faculty Block 3",
    },
    {
      _id: "leave-1",
      tenantId,
      category: "leave-request",
      studentName: "Rahul Nayak",
      studentId: "CGU2024CSE001",
      semester: 6,
      section: "A",
      fromDate: "2026-04-28",
      toDate: "2026-04-29",
      reason: "Family function",
      status: "pending",
    },
    {
      _id: "curriculum-1",
      tenantId,
      category: "curriculum-plan",
      program: "B.Tech CSE",
      semester: 6,
      title: "AI Elective Revision",
      status: "pending",
      revision: "2026-R2",
      owner: "Academic Office",
    },
    {
      _id: "approval-1",
      tenantId,
      category: "approval",
      itemType: "Curriculum",
      title: "Updated elective basket",
      status: "pending",
      requestedBy: "Dean Academics",
      approvedBy: "",
    },
    {
      _id: "record-1",
      tenantId,
      category: "record",
      recordType: "Accreditation",
      referenceNo: "NAAC-2026-04",
      title: "Semester teaching evidence",
      owner: "Quality Office",
      notes: "Ready for review",
    },
  ];
}
