export const adminAccounts = [
  {
    id: "admin-super-1",
    tenantId: "cgu",
    username: "superadmin",
    password: "Admin@1234",
    role: "ADMIN",
    name: "AYRA Super Admin",
    email: "superadmin@erp-system.com",
    allowedPortals: ["masterAdmin", "academics", "accounts", "hr"],
  },
  {
    id: "admin-academic-1",
    tenantId: "cgu",
    username: "academics",
    password: "Academic@123",
    role: "ACADEMICS",
    name: "Academic Office",
    email: "academics@ayra.local",
    allowedPortals: ["academics"],
  },
  {
    id: "admin-finance-1",
    tenantId: "cgu",
    username: "accounts",
    password: "Finance@123",
    role: "FINANCE",
    name: "Finance Desk",
    email: "accounts@ayra.local",
    allowedPortals: ["accounts"],
  },
];

export const userAccounts = [
  {
    id: "student-user-1",
    tenantId: "cgu",
    role: "STUDENT",
    username: "student1",
    password: "Student@123",
    displayName: "Aarav Student",
    profile: {
      studentId: "CGU-ST-001",
      fullName: "Aarav Student",
      department: "CSE",
      semester: 6,
      section: "A",
      cgpa: 8.6,
      sgpa: 8.8,
    },
  },
  {
    id: "teacher-user-1",
    tenantId: "cgu",
    role: "TEACHER",
    username: "teacher1",
    password: "Teacher@123",
    displayName: "Meera Faculty",
    profile: {
      employeeId: "CGU-TE-009",
      department: "CSE",
      designation: "Assistant Professor",
    },
  },
  {
    id: "academic-user-1",
    tenantId: "cgu",
    role: "ACADEMICS",
    username: "academic1",
    password: "Academic@123",
    displayName: "Academic Coordinator",
    profile: {
      department: "Academic Office",
      designation: "Coordinator",
    },
  },
  {
    id: "communication-user-1",
    tenantId: "cgu",
    role: "COMMUNICATION",
    username: "communication1",
    password: "Comm@123",
    displayName: "Communication Officer",
    profile: {
      department: "Communication",
      designation: "Officer",
    },
  },
];
