export function getDashboardLegacyCollections(tenantId = "cgu") {
  return {
    "communication/students": [],
    "communication/announcements": [
      {
        _id: "announcement-1",
        tenantId,
        title: "Semester Registration Window",
        content: "Registration remains open until April 30 for all departments.",
        audience: "All Students",
        channel: "Portal",
        status: "accept",
      },
    ],
    "communication/campaigns": [
      {
        _id: "campaign-1",
        tenantId,
        title: "Admission Outreach",
        audience: "Prospective Students",
        startDate: "2026-05-01",
        endDate: "2026-06-15",
        status: "accept",
      },
    ],
    "communication/events": [
      {
        _id: "comm-event-1",
        tenantId,
        year: 2026,
        eventDate: "2026-05-14",
        eventName: "Campus Hackathon",
        eventType: "Hackathon",
        venue: "Innovation Lab",
        coordinator: "Media Cell",
        audience: "All Students",
      },
    ],
    "communication/alerts": [],
    "communication/responses": [
      {
        _id: "response-1",
        tenantId,
        sourceType: "Email",
        title: "Hackathon Campaign Follow-Up",
        responseRate: 74,
        escalations: 2,
        notes: "Strong open rate from 3rd year students.",
      },
    ],
    "communication/hostel-rooms": [
      {
        _id: "hostel-room-1",
        tenantId,
        roomCode: "BH-A-201",
        hostelName: "Boys Hostel A",
        hostelCategory: "Boys",
        floorNumber: 2,
        roomNumber: "201",
        roomType: "AC 2 Bed",
        totalBeds: 2,
        availableBeds: 1,
        annualFee: 85000,
        availabilityStatus: "Available",
      },
    ],
    "communication/hostel-allocations": [
      {
        _id: "hostel-allocation-1",
        tenantId,
        studentId: "CGU2024CSE002",
        studentName: "Ananya Das",
        hostelName: "Girls Hostel A",
        roomNumber: "108",
        bedNumber: "2",
        paymentStatus: "Pending",
      },
    ],
    "communication/transport-routes": [
      {
        _id: "route-1",
        tenantId,
        routeCode: "BBR-01",
        busNumber: "Bus-07",
        city: "Bhubaneswar",
        routeName: "Patia to Campus",
        busType: "AC",
        capacity: 40,
        availableSeats: 8,
        driverName: "R. Pradhan",
        driverPhone: "9555511111",
        pickupPoints: ["Patia", "KIIT Square", "Infocity"],
        monthlyFee: 3200,
        routeStatus: "Active",
      },
    ],
    "communication/transport-allocations": [
      {
        _id: "transport-allocation-1",
        tenantId,
        studentId: "CGU2024CSE001",
        studentName: "Rahul Nayak",
        busNumber: "Bus-07",
        routeName: "Patia to Campus",
        seatNumber: "12",
        pickupPoint: "KIIT Square",
        paymentStatus: "Paid",
      },
    ],
  };
}
