export function getStudentSeedData(tenantId = "cgu") {
  return [
    {
      _id: "student-profile-1",
      tenantId,
      username: "student1",
      studentId: "CGU2024CSE001",
      fullName: "Rahul Nayak",
      displayName: "Rahul Nayak",
      department: "CSE",
      semester: 6,
      section: "A",
      email: "student1@cgu.edu.in",
      phone: "9876543210",
      sgpa: 8.6,
      cgpa: 8.74,
      status: "accept",
    },
    {
      _id: "student-profile-2",
      tenantId,
      username: "student2",
      studentId: "CGU2024CSE002",
      fullName: "Ananya Das",
      displayName: "Ananya Das",
      department: "CSE",
      semester: 6,
      section: "A",
      email: "student2@cgu.edu.in",
      phone: "9123456780",
      sgpa: 8.2,
      cgpa: 8.41,
      status: "accept",
    },
    {
      _id: "student-profile-3",
      tenantId,
      username: "student3",
      studentId: "CGU2024CSE003",
      fullName: "Priya Mishra",
      displayName: "Priya Mishra",
      department: "CSE",
      semester: 6,
      section: "A",
      email: "student3@cgu.edu.in",
      phone: "9988776655",
      sgpa: 8.9,
      cgpa: 9.02,
      status: "accept",
    },
  ];
}
